-- AP Auto Parts — import TATA truck-parts catalogue (44 products, 6 categories).
-- Replaces the placeholder samples. Safe to run more than once.
BEGIN;

-- 1) Remove the old placeholder sample catalogue
DELETE FROM "StockMovement" WHERE "productId" IN (SELECT id FROM "Product" WHERE slug IN ('piston-ring-set','cylinder-head-gasket','brake-pad-set-front','brake-disc-rotor','shock-absorber-rear','control-arm-bush-kit','clutch-plate-assembly','alternator-12v-90a'));
UPDATE "Enquiry" SET "productId"=NULL WHERE "productId" IN (SELECT id FROM "Product" WHERE slug IN ('piston-ring-set','cylinder-head-gasket','brake-pad-set-front','brake-disc-rotor','shock-absorber-rear','control-arm-bush-kit','clutch-plate-assembly','alternator-12v-90a'));
DELETE FROM "OrderItem" WHERE "productId" IN (SELECT id FROM "Product" WHERE slug IN ('piston-ring-set','cylinder-head-gasket','brake-pad-set-front','brake-disc-rotor','shock-absorber-rear','control-arm-bush-kit','clutch-plate-assembly','alternator-12v-90a'));
DELETE FROM "Product" WHERE slug IN ('piston-ring-set','cylinder-head-gasket','brake-pad-set-front','brake-disc-rotor','shock-absorber-rear','control-arm-bush-kit','clutch-plate-assembly','alternator-12v-90a');
DELETE FROM "Category" WHERE slug IN ('engine-parts','brake-systems','suspension','transmission','electrical');

-- 2) Categories
INSERT INTO "Category" ("id","name","slug") VALUES ('cat_eng','Engine & Motor Mounts','engine-motor-mounts') ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Category" ("id","name","slug") VALUES ('cat_cab','Cabin Mounts','cabin-mounts') ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Category" ("id","name","slug") VALUES ('cat_lcm','Load Cushion Mounts','load-cushion-mounts') ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Category" ("id","name","slug") VALUES ('cat_trb','Torque Rod Bushes','torque-rod-bushes') ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Category" ("id","name","slug") VALUES ('cat_bush','Bushes','bushes') ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Category" ("id","name","slug") VALUES ('cat_lax','Lift Axle Parts','lift-axle-parts') ON CONFLICT ("slug") DO NOTHING;

-- 3) Products
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3001','Load Cushion Mount','load-cushion-mount-3001','AP-3001','Load Cushion Mount for TATA TP 2528 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA TP 2528 Series Trucks","OEM Ref":"500632400130","Pack Size":"2"}',5450,'8708','/products/tata/ap-3001.png',true,true,'cat_lcm',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3002','Load Cushion Mount (Heavy Duty)','load-cushion-mount-heavy-duty-3002','AP-3002','Load Cushion Mount (Heavy Duty) for TATA TP 2528 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA TP 2528 Series Trucks","OEM Ref":"500632400130","Pack Size":"2"}',5730,'8708','/products/tata/ap-3002.png',true,false,'cat_lcm',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3003','Load Cushion Mount','load-cushion-mount-3003','AP-3003','Load Cushion Mount for TATA 2518, 2523 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA 2518, 2523 Series Trucks","OEM Ref":"501132400106","Pack Size":"2"}',5450,'8708','/products/tata/ap-3003.png',true,false,'cat_lcm',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3004','Load Cushion Mount (Heavy Duty)','load-cushion-mount-heavy-duty-3004','AP-3004','Load Cushion Mount (Heavy Duty) for TATA Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Series Trucks","Pack Size":"2"}',5730,'8708','/products/tata/ap-3004.png',true,false,'cat_lcm',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3151','Load Cushion Mount','load-cushion-mount-3151','AP-3151','Load Cushion Mount for TATA Trucks BS6 Series. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Trucks BS6 Series","OEM Ref":"506632400145","Pack Size":"2"}',5400,'8708','/products/tata/ap-3151.png',true,false,'cat_lcm',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3005','Centre Bush (A-Frame)','centre-bush-a-frame-3005','AP-3005','Centre Bush (A-Frame) for TATA 2518, 2523 Series Trucks — A-Frame Centre Bush. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA 2518, 2523 Series Trucks — A-Frame Centre Bush","OEM Ref":"501132400115","Pack Size":"6"}',2600,'8708','/products/tata/ap-3005.png',true,false,'cat_bush',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3127','Centre Bush (A-Frame)','centre-bush-a-frame-3127','AP-3127','Centre Bush (A-Frame) for TATA 2518, 2523 Series Trucks — A-Frame Centre Bush. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA 2518, 2523 Series Trucks — A-Frame Centre Bush","OEM Ref":"501132400115","Pack Size":"6"}',2763,'8708','/products/tata/ap-3127.png',true,false,'cat_bush',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3006','Centre Bush (A-Frame, Set of 3)','centre-bush-a-frame-set-of-3-3006','AP-3006','Centre Bush (A-Frame, Set of 3) for TATA Prima Trucks — A-Frame Centre Bush, Set of 3 Pcs. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Prima Trucks — A-Frame Centre Bush, Set of 3 Pcs","Pack Size":"6"}',6600,'8708','/products/tata/ap-3006.png',true,false,'cat_bush',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3150','Trunnion Bush','trunnion-bush-3150','AP-3150','Trunnion Bush for TATA Prima Series Trucks, BS6 Model. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Prima Series Trucks, BS6 Model","OEM Ref":"506632400167","Pack Size":"4"}',2600,'8708','/products/tata/ap-3150.png',true,false,'cat_bush',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3007','Bogi Bush (Nylon)','bogi-bush-nylon-3007','AP-3007','Bogi Bush (Nylon) for TATA Prima Trucks New Models. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Prima Trucks New Models","Pack Size":"16"}',676,'8708','/products/tata/ap-3007.png',true,false,'cat_bush',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3008','Bogi Bush (Nylon)','bogi-bush-nylon-3008','AP-3008','Bogi Bush (Nylon) for TATA 4018, 3118 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA 4018, 3118 Series Trucks","OEM Ref":"501132403401","Pack Size":"16"}',650,'8708','/products/tata/ap-3008.png',true,false,'cat_bush',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3009','Torque Rod Bush 95mm','torque-rod-bush-95mm-3009','AP-3009','Torque Rod Bush 95mm for TATA 2518, 2523 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA 2518, 2523 Series Trucks","OEM Ref":"501132400111","Pack Size":"6","Size":"95mm"}',2650,'8708','/products/tata/ap-3009.png',true,true,'cat_trb',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3011','Torque Rod Bush 100mm','torque-rod-bush-100mm-3011','AP-3011','Torque Rod Bush 100mm for TATA 2518 TP, 2523 TP, Prima 4849 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA 2518 TP, 2523 TP, Prima 4849 Series Trucks","OEM Ref":"500632400126","Pack Size":"6","Size":"100mm"}',3006,'8708','/products/tata/ap-3011.png',true,false,'cat_trb',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3012','Torque Rod Bush 108mm','torque-rod-bush-108mm-3012','AP-3012','Torque Rod Bush 108mm for TATA LPK 2523 TC BS2 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA LPK 2523 TC BS2 Series Trucks","Pack Size":"6","Size":"108mm"}',3800,'8708','/products/tata/ap-3012.png',true,false,'cat_trb',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3072','Torque Rod Bush 75mm','torque-rod-bush-75mm-3072','AP-3072','Torque Rod Bush 75mm for TATA Signa 4923 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Signa 4923 Series Trucks","Pack Size":"6","Size":"75mm"}',2560,'8708','/products/tata/ap-3072.png',true,false,'cat_trb',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3149','Torque Rod Bush BS6 108mm','torque-rod-bush-bs6-108mm-3149','AP-3149','Torque Rod Bush BS6 108mm for TATA Series Trucks BS6. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Series Trucks BS6","OEM Ref":"229032400190","Pack Size":"6","Size":"108mm"}',4150,'8708','/products/tata/ap-3149.png',true,false,'cat_trb',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3014','Lift Axle Bushing Kit 25mm','lift-axle-bushing-kit-25mm-3014','AP-3014','Lift Axle Bushing Kit 25mm for TATA TP2518, TP2523, TP1210, TP2528 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA TP2518, TP2523, TP1210, TP2528 Series Trucks","Pack Size":"12","Size":"25mm"}',1008,'8708','/products/tata/ap-3014.png',true,false,'cat_lax',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3016','Lift Axle Bushing Kit 27mm','lift-axle-bushing-kit-27mm-3016','AP-3016','Lift Axle Bushing Kit 27mm for TATA 3118 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA 3118 Series Trucks","OEM Ref":"284633900150S","Pack Size":"12","Size":"27mm"}',1056,'8708','/products/tata/ap-3016.png',true,false,'cat_lax',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3018','Lift Axle Washer','lift-axle-washer-3018','AP-3018','Lift Axle Washer for TATA TP2518, TP2523, TP1210, TP2528 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA TP2518, TP2523, TP1210, TP2528 Series Trucks","Pack Size":"50"}',200,'8708','/products/tata/ap-3018.png',true,false,'cat_lax',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3020','Engine Mount','engine-mount-3020','AP-3020','Engine Mount for TATA 1210 Truck Series. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA 1210 Truck Series","Pack Size":"12"}',982,'8708','/products/tata/ap-3020.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3021','Engine Mount Front 16mm','engine-mount-front-16mm-3021','AP-3021','Engine Mount Front 16mm for TATA 1312 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA 1312 Series Trucks","OEM Ref":"257324100103","Pack Size":"12","Size":"16mm"}',800,'8708','/products/tata/ap-3021.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3022','Engine Mount Front 14mm','engine-mount-front-14mm-3022','AP-3022','Engine Mount Front 14mm for TATA 1312 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA 1312 Series Trucks","OEM Ref":"257624100101","Pack Size":"12","Size":"14mm"}',800,'8708','/products/tata/ap-3022.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3024','Engine Mount Rear (4 Bolt)','engine-mount-rear-4-bolt-3024','AP-3024','Engine Mount Rear (4 Bolt) for TATA Trucks Rear Engine Mounting. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Trucks Rear Engine Mounting","OEM Ref":"257624200118","Pack Size":"12"}',775,'8708','/products/tata/ap-3024.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3026','Engine Mount, LH Rear','engine-mount-lh-rear-3026','AP-3026','Engine Mount, LH Rear for TATA 1312 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA 1312 Series Trucks","OEM Ref":"257524200102","Pack Size":"12"}',1125,'8708','/products/tata/ap-3026.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3027','Engine Mount, RH Rear','engine-mount-rh-rear-3027','AP-3027','Engine Mount, RH Rear for TATA 1312 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA 1312 Series Trucks","OEM Ref":"257624200101","Pack Size":"12"}',1125,'8708','/products/tata/ap-3027.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3028','Engine Mount, LH Rear','engine-mount-lh-rear-3028','AP-3028','Engine Mount, LH Rear for TATA TC Euro 2 Truck Series. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA TC Euro 2 Truck Series","Pack Size":"12"}',1203,'8708','/products/tata/ap-3028.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3029','Engine Mount, RH Rear','engine-mount-rh-rear-3029','AP-3029','Engine Mount, RH Rear for TATA TC Euro 2 Truck Series. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA TC Euro 2 Truck Series","Pack Size":"12"}',1203,'8708','/products/tata/ap-3029.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3030','Engine Mount, LH Rear','engine-mount-lh-rear-3030','AP-3030','Engine Mount, LH Rear for TATA TC Euro 3 Truck Series. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA TC Euro 3 Truck Series","Pack Size":"12"}',1203,'8708','/products/tata/ap-3030.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3031','Engine Mount, RH Rear','engine-mount-rh-rear-3031','AP-3031','Engine Mount, RH Rear for TATA TC Euro 3 Truck Series. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA TC Euro 3 Truck Series","Pack Size":"12"}',1203,'8708','/products/tata/ap-3031.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3032','Engine Mount, Rear','engine-mount-rear-3032','AP-3032','Engine Mount, Rear for TATA SE Truck Series. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA SE Truck Series","Pack Size":"12"}',1056,'8708','/products/tata/ap-3032.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3055','Engine Mount','engine-mount-3055','AP-3055','Engine Mount for TATA Prima Truck Series. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Prima Truck Series"}',1250,'8708','/products/tata/ap-3055.png',true,true,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3056','Motor Mount','motor-mount-3056','AP-3056','Motor Mount for TATA Prima LPK 40.8 Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Prima LPK 40.8 Series Trucks","OEM Ref":"288024000105"}',449,'8708','/products/tata/ap-3056.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3061','Engine Mount 12mm (BS IV Rear)','engine-mount-12mm-bs-iv-rear-3061','AP-3061','Engine Mount 12mm (BS IV Rear) for TATA BS IV Rear Engine Mounting. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA BS IV Rear Engine Mounting","OEM Ref":"505324200103","Pack Size":"6","Size":"12mm"}',2750,'8708','/products/tata/ap-3061.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3063','Engine Mount, Front LH','engine-mount-front-lh-3063','AP-3063','Engine Mount, Front LH for TATA Ultra Truck Series. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Ultra Truck Series"}',1450,'8708','/products/tata/ap-3063.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3064','Engine Mount, Front RH','engine-mount-front-rh-3064','AP-3064','Engine Mount, Front RH for TATA Ultra Truck Series. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Ultra Truck Series"}',1450,'8708','/products/tata/ap-3064.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3065','Engine Mount Rear (BS4)','engine-mount-rear-bs4-3065','AP-3065','Engine Mount Rear (BS4) for TATA Ultra Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Ultra Series Trucks"}',2005,'8708','/products/tata/ap-3065.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3075','Engine Mount 16mm (BS IV Rear)','engine-mount-16mm-bs-iv-rear-3075','AP-3075','Engine Mount 16mm (BS IV Rear) for TATA BS IV Rear Engine Mounting. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA BS IV Rear Engine Mounting","OEM Ref":"505324200103","Pack Size":"6","Size":"16mm"}',2650,'8708','/products/tata/ap-3075.png',true,false,'cat_eng',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3034','Cabin Mount','cabin-mount-3034','AP-3034','Cabin Mount for TATA 2416/1516 Truck Series. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA 2416/1516 Truck Series"}',260,'8708','/products/tata/ap-3034.png',true,false,'cat_cab',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3036','Cabin Mount','cabin-mount-3036','AP-3036','Cabin Mount for TATA 2416/1516 Truck Series. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA 2416/1516 Truck Series"}',262,'8708','/products/tata/ap-3036.png',true,false,'cat_cab',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3057','Cabin Mount Bush','cabin-mount-bush-3057','AP-3057','Cabin Mount Bush for TATA Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Series Trucks","OEM Ref":"A9423172012","Pack Size":"12"}',2250,'8708','/products/tata/ap-3057.png',true,false,'cat_cab',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3058','Cabin Mount RH','cabin-mount-rh-3058','AP-3058','Cabin Mount RH for TATA Signa Cabin Mounting Assembly RH. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Signa Cabin Mounting Assembly RH","OEM Ref":"268089100113","Pack Size":"2"}',4850,'8708','/products/tata/ap-3058.png',true,true,'cat_cab',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3059','Cabin Mount LH','cabin-mount-lh-3059','AP-3059','Cabin Mount LH for TATA Signa Cabin Mounting Assembly LH. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Signa Cabin Mounting Assembly LH","OEM Ref":"268089100112","Pack Size":"2"}',4850,'8708','/products/tata/ap-3059.png',true,false,'cat_cab',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3070','Cabin Leaf Spring Mount','cabin-leaf-spring-mount-3070','AP-3070','Cabin Leaf Spring Mount for TATA Series Trucks. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA Series Trucks"}',731,'8708','/products/tata/ap-3070.png',true,false,'cat_cab',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Product" ("id","name","slug","partNumber","description","specs","price","hsnCode","imageUrl","isPublished","isFeatured","categoryId","updatedAt") VALUES ('prod_3074','Cabin Mount','cabin-mount-3074','AP-3074','Cabin Mount for TATA 2416/1512 Truck Series. Rubber-to-metal bonded component manufactured to OEM standards.','{"Application":"TATA 2416/1512 Truck Series"}',683,'8708','/products/tata/ap-3074.png',true,false,'cat_cab',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;

-- 4) Opening stock (50 each), only if the product has no movements yet
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3001','prod_3001',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3001');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3002','prod_3002',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3002');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3003','prod_3003',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3003');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3004','prod_3004',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3004');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3151','prod_3151',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3151');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3005','prod_3005',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3005');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3127','prod_3127',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3127');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3006','prod_3006',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3006');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3150','prod_3150',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3150');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3007','prod_3007',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3007');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3008','prod_3008',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3008');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3009','prod_3009',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3009');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3011','prod_3011',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3011');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3012','prod_3012',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3012');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3072','prod_3072',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3072');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3149','prod_3149',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3149');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3014','prod_3014',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3014');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3016','prod_3016',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3016');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3018','prod_3018',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3018');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3020','prod_3020',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3020');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3021','prod_3021',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3021');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3022','prod_3022',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3022');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3024','prod_3024',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3024');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3026','prod_3026',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3026');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3027','prod_3027',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3027');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3028','prod_3028',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3028');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3029','prod_3029',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3029');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3030','prod_3030',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3030');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3031','prod_3031',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3031');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3032','prod_3032',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3032');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3055','prod_3055',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3055');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3056','prod_3056',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3056');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3061','prod_3061',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3061');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3063','prod_3063',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3063');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3064','prod_3064',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3064');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3065','prod_3065',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3065');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3075','prod_3075',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3075');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3034','prod_3034',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3034');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3036','prod_3036',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3036');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3057','prod_3057',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3057');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3058','prod_3058',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3058');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3059','prod_3059',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3059');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3070','prod_3070',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3070');
INSERT INTO "StockMovement" ("id","productId","delta","reason","note") SELECT 'sm_3074','prod_3074',50,'ADJUSTMENT','Opening stock' WHERE NOT EXISTS (SELECT 1 FROM "StockMovement" WHERE "productId"='prod_3074');

COMMIT;
